### ISSUE TITLE
Face detection failure

### ISSUE THREAD

**Issue by iamlaobie** [espressif/esp-face#2]
I am developing a face recognizing by ESP-EYE, But the face detection fail every frequently.
I found the P-Net result is OK, but the R-Net return NULL when I input e normal face.
Could I do something refine it?
Thanks!

**Comment by XiaochaoGONG** [comment]
Hi, you can modify the threshold for the R-Net and O-Net,
https://github.com/espressif/esp-face/blob/a28b3a9292b10e01ea491c602d69f541970f0432/face_detection/include/fd_forward.h#L43-L45

**Comment by iamlaobie** [comment]
Thanks for your reply!
Try many times, I found the reason is the distance too close between my face and the camera!
When I hold the board by my hand, the distance is about 20 or 30 cm. I use a simple shelf hold the board and the distance is about 50 cm,  the result is perfect!
Thanks again!
