### ISSUE TITLE
Referencing Work

### ISSUE THREAD

**Issue by caleb221** [espressif/esp-face#20]
Hi!
Not an issue, but I was wondering if you have a preference on how I should cite this library in academic work?
Currently I am citing it with the link on Github, but I'm unsure who to attribute the work to.
Thanks!
-Caleb

**Comment by XiaochaoGONG** [comment]
Hi, you can attribute the work to Espressif

**Comment by caleb221** [comment]
Ok great, 
Thank you for all your help these past few months, 
I greatly appreciate it!
