### ISSUE TITLE
In <dl_matrix3dff_conv_common> function the bias weights are not taken into account.

### ISSUE THREAD

**Issue by Vvard** [espressif/esp-face#26]
![input](https://user-images.githubusercontent.com/54348801/76404290-a789d780-639f-11ea-9e96-dac5b7d2a335.PNG)
![cnn3x3_with_1_bias_weight](https://user-images.githubusercontent.com/54348801/76404315-b40e3000-639f-11ea-8b24-0a7f38c7eaa2.PNG)
![cnn3x3_with_0_bias_weight](https://user-images.githubusercontent.com/54348801/76404318-b53f5d00-639f-11ea-88b6-5144588f784d.PNG)
![one conv layer](https://user-images.githubusercontent.com/54348801/76404333-bc666b00-639f-11ea-927b-63f1ffddd0b7.PNG)
![conv_output_with_1_bias_weight](https://user-images.githubusercontent.com/54348801/76404349-bff9f200-639f-11ea-9a23-7aa78912004b.PNG)
![conv_output_with_0_bias_weight](https://user-images.githubusercontent.com/54348801/76404354-c0928880-639f-11ea-8885-3b0837c4f378.PNG)

I used "dl_matrix3dff_conv_common(dl_matrix3d_t *in, dl_matrix3d_t *filter, dl_matrix3d_t *bias, int stride_x, int stride_y, dl_padding_type padding)" function with different bias weights, but there are no changing results. This is a small test program with 4x4 input data, where I run the program in the case of 0 bias weight and in the case of 1 bias weight and I get the same result.

**Comment by XiaochaoGONG** [comment]
Good test ! I'll fix that.

**Comment by XiaochaoGONG** [comment]
f1a3dbe8ffe418aa6f9372831f9c1e33a651ab5b Please update and try.

**Comment by Vvard** [comment]
Works correctly! thanks)
