### ISSUE TITLE
PADDING_SAME_DONT_FREE_INPUT padding type description

### ISSUE THREAD

**Issue by Vvard** [espressif/esp-face#27]
Could you describe the padding type PADDING_SAME_DONT_FREE_INPUT in dl_lib matrix3d.h?

**Comment by Vvard** [comment]
And there is complete documentation for the DL API?

**Comment by XiaochaoGONG** [comment]
Hi I'll update the documentation of dl_lib. Please wait for a while, maybe next week.
For short, the PADDING_SAME flag indicates the process would free the input matrix when finish padding, while PADDING_SAME_DONT_FREE_INPUT indicates the input matrix remain. Both of PADDING_SAME will give you a new allocated padded input.
- PADDING_SAME: input --> return malloc padded input and free input
- PADDING_SAME_DONT_FREE: input --> return malloc padded input

**Comment by Vvard** [comment]
OK, thanks)
