### ISSUE TITLE
Can I get the code of the DL framework?

### ISSUE THREAD

**Issue by geekboood** [espressif/esp-face#8]
Hi, currently I am trying to use ESP32 to run DL algorithms and my algorithm is a variant of MobileNet. I wonder whether I could get the code of this DL framework for further development. Thank you.

**Comment by XiaochaoGONG** [comment]
Hi, in the future we will release a simple guide to implement your own algorithms and models.

**Comment by mattiantonini** [comment]
Hi @XiaochaoGONG! Is there any update about code release or how to implement custom models?
Thanks, 

Mattia

**Comment by XiaochaoGONG** [comment]
Hi all, please see 8a6e07ae102aeca1f3ee8d418804d8914952d4c9, it's a basic application to inspire implementing your own models.
